'use client';
import {
  experimental_extendTheme as materialExtendTheme,
  Experimental_CssVarsProvider as MaterialCssVarsProvider,
  THEME_ID as MATERIAL_THEME_ID,
} from '@mui/material/styles';
import { CssVarsProvider as JoyCssVarsProvider } from '@mui/joy/styles';
import CssBaseline from '@mui/material/CssBaseline';

import ThemeRegistry from './ThemeRegistry';

import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const materialTheme = materialExtendTheme();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <MaterialCssVarsProvider theme={{ [MATERIAL_THEME_ID]: materialTheme }}>
          <JoyCssVarsProvider>
            <ThemeRegistry options={{ key: 'joy' }}>
              <CssBaseline />
              {children}
            </ThemeRegistry>
          </JoyCssVarsProvider>
        </MaterialCssVarsProvider>
      </body>
    </html>
  );
}
